parameters:
    open_orchestra_api.oauth2.authorization_server.class: OpenOrchestra\BaseApi\OAuth2\AuthorizationServer
    open_orchestra_api.oauth2.strategy.client_credentials_grant.class: OpenOrchestra\BaseApi\OAuth2\Strategy\ClientCredentialsGrantStrategy
    open_orchestra_api.oauth2.strategy.refresh_token.class: OpenOrchestra\BaseApi\OAuth2\Strategy\RefreshTokenStrategy

services:
    open_orchestra_api.oauth2.authorization_server:
        class: '%open_orchestra_api.oauth2.authorization_server.class%'
    open_orchestra_api.oauth2.strategy.client_credentials_grant:
        class: '%open_orchestra_api.oauth2.strategy.client_credentials_grant.class%'
        arguments:
            - '@open_orchestra_api.repository.api_client'
            - '@serializer'
            - '@validator'
            - '@open_orchestra_api.manager.access_token'
            - '@open_orchestra_api.repository.access_token'
        tags:
            - { name: open_orchestra_api.oauth2.strategy }
    open_orchestra_api.oauth2.strategy.refresh_token:
        class: '%open_orchestra_api.oauth2.strategy.refresh_token.class%'
        arguments:
            - '@open_orchestra_api.repository.api_client'
            - '@serializer'
            - '@validator'
            - '@open_orchestra_api.manager.access_token'
            - '@open_orchestra_api.repository.access_token'
        tags:
            - { name: open_orchestra_api.oauth2.strategy }
